<div dir='rtl'>
<ol>
    <li>المنتج الأكثر مبيعاً: ما هي فئة المنتج (Product Category) التي حققت أعلى إجمالي مبيعات (Total Amount)؟</li>
    <li>
        سلوك الشراء حسب الجنس: قم بعمل جدول محوري يوضح إجمالي المبيعات (Total Amount)، مقسماً حسب فئة المنتج (Product Category) في الصفوف، وجنس العميل (Gender) في الأعمدة.
    </li>
    <li>متوسط الكميات: ما هي فئة المنتج التي يشتري منها العملاء أعلى "متوسط" للكمية (Quantity) في الفاتورة الواحدة؟</li>
    <li>عدد الفواتير: كم عدد الفواتير (استخدم count لعمود Transaction ID) التي قام بها الرجال مقارنة بالنساء؟</li>
    <li>
        تقرير الإدارة الشامل (سؤال التميز): قم بإنشاء جدول محوري يعرض إجمالي المبيعات (Total Amount) لكل فئة منتج، مقسماً على الجنس، مع إضافة عمود وصف "الإجمالي الكلي" (margins=True).
    </li>
</ol>
</div>

In [1]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv(
    "retail_sales_dataset.csv",
    dtype={
        "Transaction ID": np.uint16,
        "Age": np.uint8,
        "Quantity": np.uint8,
        "Price per Unit": np.uint16,
        "Total Amount": np.uint16,
    },
    parse_dates=["Date"],
)
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [31]:
df.groupby("Product Category")[['Total Amount']].sum().sort_values("Total Amount", ascending=False)

                  Total Amount
Product Category
Electronics             156905
Clothing                155580
Beauty                  143515

In [32]:
pd.pivot_table(
    data=df,
    values="Total Amount",
    index="Product Category",
    aggfunc='sum',
).sort_values("Total Amount", ascending=False)

                  Total Amount
Product Category
Electronics             156905
Clothing                155580
Beauty                  143515

In [33]:
pd.pivot_table(
    data=df,
    values="Total Amount",
    index="Product Category",
    columns="Gender",
    aggfunc="sum"
)

Gender            Female   Male
Product Category
Beauty             74830  68685
Clothing           81275  74305
Electronics        76735  80170

In [34]:
pd.pivot_table(
    data=df,
    index='Product Category',
    values='Quantity'
)

                  Quantity
Product Category
Beauty            2.511401
Clothing          2.547009
Electronics       2.482456

In [37]:
pd.pivot_table(
    data=df,
    values="Transaction ID",
    index="Gender",
    aggfunc='count'
)

        Transaction ID
Gender
Female             510
Male               490

In [38]:
pd.pivot_table(
    data=df,
    values="Total Amount",
    index="Gender",
    columns="Product Category",
    aggfunc='sum',
    margins=True,
    margins_name="Total"
)

Product Category  Beauty  Clothing  Electronics   Total
Gender
Female             74830     81275        76735  232840
Male               68685     74305        80170  223160
Total             143515    155580       156905  456000